version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - wp-network
      
  wordpress:
    depends_on:
      - db
    image: wordpress:6.6.2-php8.1-apache
    container_name: wordpress
    env_file: .env
    ports:
      - 80:80
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - wp-network

volumes:
  wordpress:
  dbdata:

networks:
  wp-network:
    driver: bridge      
 
